### ISSUE TITLE
Unable to read SystemAppearance.car

### ISSUE THREAD

**Issue by jakepetroules** [insidegui/AssetCatalogTinkerer#14]
The app can't read SystemAppearance.car because it thinks it's an asset catalog file, when it's actually a theme store. The check:

    if (!self.catalog.allImageNames.count || ![self.catalog respondsToSelector:@selector(imageWithName:scaleFactor:)]) {
        // CAR is a theme file not an asset catalog
        return [self readThemeStoreWithCompletionHandler:callback progressHandler:progressCallback];
    }

fails, because catalog.allImageNames contains a single "_UIKitNewLetterpressStyle" item. Maybe it should check if catalog._themeStore is non-`nil`?

**Comment by insidegui** [comment]
Turns out this distinction between catalogs and theme stores is not really necessary, but with the current implementation, opening regular catalogs (from apps) through the theme store interpreter makes the file names not as concise. The solution I've found to this is to add preferences to the app so the user can choose whether the reader should treat the stores differently. I've also added a preference to ignore `ZZPackedAsset` files which are present in some catalogs.

![screen shot 2017-02-22 at 10 14 04](https://cloud.githubusercontent.com/assets/67184/23213262/0df27682-f8e9-11e6-85cc-3de23d153dfe.png)
